# Get MOOSE image with deps
FROM awhittle/proteus-deps-ubuntu:v.0.3.1

# By default 4 cores are used to compile
ARG compile_cores=4

# Should we generate a coverage report
ARG test_coverage=false

# Coverage repo token
ARG coveralls_token=""

# Branch name for coveralls
ARG coveralls_branch=""

Change this for git
