name: C/C++ Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Ubuntu pre-requisites
      run: ./scripts/install_ubuntu_prerequisites.sh
    - name: Ubuntu based build
      run: ./scripts/install_ubuntu.sh
    - name: Source Proteus profile and run tests
      run: source "$HOME/.proteus_profile"; ./run_tests
